services:
  db:
    image: 'postgres:15'
    container_name: todo_list_db
    environment:
      - POSTGRES_USER=todo_list
      - POSTGRES_PASSWORD=todo_list
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo_list_network

networks:
  todo_list_network:
    driver: bridge

volumes:
    pgdata: