spring:
  application:
    name: todo-list
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_list
    username: todo_list
    password: todo_list
